#!/usr/bin/env node
const { TeeworldsServer } = require('teeworlds-info');
const { parseHost, parsePort, parseTimeout, isConfig, waterfall } = require('./utils');

const host = parseHost(process.argv[1]);
const port = parsePort(process.argv[1]);
const timeout = parseTimeout(process.env.timeout);

if (!host) {
  console.error('Undefined host');
  process.exit(-1);
}
if (!port) {
  console.error('Undefined port');
  process.exit(-1);
}

const printConfig = () => {
  console.log('graph_title Ping to %s:%s Teeworlds Server', host, port);
  console.log('graph_vlabel roundtrip time (seconds)');
  console.log('graph_category teeworlds');
  console.log('ping.label %s:%s', host, port);
};

const printValues = () => {
  const server = new TeeworldsServer(host, port);

  const results = [];
  const jobs = Array(4).fill(() => {
    const promise = server.ping(timeout);
    return promise.then((result) => results.push(result));
  });

  waterfall(jobs).then(() => {
    const avg = results.reduce((a, b) => a + b) / results.length;
    console.log('ping.value %d', avg/1000);
  }).catch(() => {
    console.log('ping.value U');
  });
};

if (isConfig(process.argv[2]))
  printConfig();
else
  printValues();
