#!/usr/bin/env node
const TeeworldsServer = require('teeworlds-info');
const { parseHost, parsePort, isConfig } = require('./utils');

const host = parseHost(process.argv[1]);
const port = parsePort(process.argv[1]);

if (!host) {
  console.error('Undefined host');
  process.exit(-1);
}
if (!port) {
  console.error('Undefined port');
  process.exit(-1);
}

const printConfig = () => {
  console.log('graph_title Teeworlds Server info for %s:%d', host, port);
  console.log('graph_vlabel players count');
  console.log('graph_category teeworlds');
  console.log('players.label online');
  console.log('spectators.label spectators');
};

const printValues = () => {
  const server = new TeeworldsServer(host, port);
  server.getInfo(5).then((info) => {
    console.log('players.value %d', info.players);
    console.log('spectators.value %d', info.spectators);
  }).catch(() => {
    console.log('players.value U');
    console.log('spectators.value U');
  });
};

if (isConfig(process.argv[2]))
  printConfig();
else
  printValues();
